name: Autorelease

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.1'

      - name: Fetch dependencies
        run: go get -u github.com/s5i/tassist

      - name: Build TAssist
        run: GOOS=windows GOARCH=amd64 go build -ldflags "-H=windowsgui -X 'github.com/s5i/goutil/version.External=${{ github.ref_name }}'" .

      - name: Build Updater
        run: GOOS=windows GOARCH=amd64 go build -C updater -ldflags "-H=windowsgui" .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: Upload TAssist
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tassist.exe
          asset_name: tassist.exe
          asset_content_type: application/octet-stream

      - name: Upload Updater
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./updater/updater.exe
          asset_name: updater.exe
          asset_content_type: application/octet-stream
